# This is a working example.
# For a more complete reference use `--example`

kibot:
  version: 1

global:
  filters:
    - number: 1007
    - number: 1015
    - number: 58
    - number: 107

import:
  - file: Elecrow
    definitions:
      _KIBOT_MANF_DIR: Manufacturers/Elecrow
  - file: FusionPCB
    definitions:
      _KIBOT_MANF_DIR: Manufacturers/FusionPCB
  - file: JLCPCB
    definitions:
      _KIBOT_MANF_DIR: Manufacturers/JLCPCB
  - file: PCBWay
    definitions:
      _KIBOT_MANF_DIR: Manufacturers/PCBWay

preflight:
  drc:
    dont_stop: true
    format: HTML,RPT,JSON,CSV
  erc:
    dont_stop: true
    format: HTML,RPT,JSON,CSV

outputs:
  - name: generic_bom_html
    comment: Generic Bill of Materials in HTML format
    type: bom
    dir: BoM
    options:
      format: HTML
      count_smd_tht: true
  - name: generic_bom_csv
    comment: Generic Bill of Materials in CSV format
    type: bom
    dir: BoM
    options:
      format: CSV
      count_smd_tht: true
  - name: generic_bom_xlsx
    comment: Generic Bill of Materials in XLSX format
    type: bom
    dir: BoM
    options:
      format: XLSX
      count_smd_tht: true

  - name: basic_excellon
    comment: Drill files in EXCELLON format
    type: excellon
    dir: Gerbers_and_Drill
    options:
      map: pdf

  - name: basic_gerb_drill
    comment: Drill files in GERB_DRILL format
    type: gerb_drill
    dir: Gerbers_and_Drill
    options:
      map: gerber
  - name: gerber_modern
    comment: Gerbers in modern format, recommended by the standard
    type: gerber
    dir: Gerbers_and_Drill
    layers:
      - layer: F.Cu
        suffix: F_Cu
        description: Front copper
      - layer: B.Cu
        suffix: B_Cu
        description: Bottom copper
      - layer: F.Paste
        suffix: F_Paste
        description: Front solder paste
      - layer: B.Paste
        suffix: B_Paste
        description: Bottom solder paste
      - layer: F.Silkscreen
        suffix: F_Silkscreen
        description: Front silkscreen (artwork)
      - layer: B.Silkscreen
        suffix: B_Silkscreen
        description: Bottom silkscreen (artwork)
      - layer: F.Mask
        suffix: F_Mask
        description: Front soldermask (negative)
      - layer: B.Mask
        suffix: B_Mask
        description: Bottom soldermask (negative)
      - layer: Edge.Cuts
        suffix: Edge_Cuts
        description: Board shape
      - layer: F.Courtyard
        suffix: F_Courtyard
        description: Front courtyard area
      - layer: B.Courtyard
        suffix: B_Courtyard
        description: Bottom courtyard area

  - name: basic_info
    comment: Information about the run
    type: info
    dir: .

  - name: basic_kicanvas
    comment: Web page to browse the schematic and/or PCB
    type: kicanvas
    dir: Browse
    options:
      source:
        - schematic
        - pcb
  - name: basic_kikit_present
    comment: Simple project presentation
    type: kikit_present
    dir: Presentation
    options:
      description: '# Presentation for TrailTrueBypass_PIC

        This is an automatically generated presentation page.'
      boards:
        mode: local
        comment: Resources included
        front_image: renderer_for_present
        back_image: renderer_for_present
        gerbers: gerbers_for_present
  - name: renderer_for_present
    comment: Renderer for the presentation
    type: pcbdraw
    dir: Render_for_presentation
    run_by_default: false
  - name: gerbers_for_present
    comment: Gerbers for the presentation
    type: gerber
    dir: Gerber_for_presentation
    layers: copper
    run_by_default: false
  - name: basic_navigate_results_rb
    comment: Web page to browse the results
    type: navigate_results_rb
    dir: Browse
    options:
      link_from_root: index.html
      skip_not_run: true

  - name: basic_pcb_print_pdf
    comment: PCB
    type: pcb_print
    dir: PCB/PDF
    options:
      format: PDF
      pages:
        - layers:
            - layer: F.Cu
            - layer: F.Mask
              color: '#14332440'
            - layer: F.Paste
            - layer: F.Silkscreen
            - layer: Edge.Cuts
          sheet: Front copper
        - layers:
            - layer: B.Cu
            - layer: B.Mask
              color: '#14332440'
            - layer: B.Silkscreen
            - layer: Edge.Cuts
          mirror: true
          sheet: Bottom copper
        - layers:
            - layer: F.Courtyard
            - layer: Edge.Cuts
          sheet: Front courtyard area
        - layers:
            - layer: F.Fab
            - layer: Edge.Cuts
          sheet: Front documentation
        - repeat_for_layer: User.Drawings
          repeat_layers: drill_pairs
          layers:
            - layer: User.Drawings
              color: '#000000'
            - layer: Edge.Cuts
              color: '#000000'
      keep_temporal_files: true
  - name: basic_pcb_print_png
    comment: PCB
    type: pcb_print
    dir: PCB/PNG
    options:
      format: PNG
      pages:
        - layers:
            - layer: F.Cu
            - layer: F.Mask
              color: '#14332440'
            - layer: F.Paste
            - layer: F.Silkscreen
            - layer: Edge.Cuts
          sheet: Front copper
        - layers:
            - layer: B.Cu
            - layer: B.Mask
              color: '#14332440'
            - layer: B.Silkscreen
            - layer: Edge.Cuts
          mirror: true
          sheet: Bottom copper
        - layers:
            - layer: F.Courtyard
            - layer: Edge.Cuts
          sheet: Front courtyard area
        - layers:
            - layer: F.Fab
            - layer: Edge.Cuts
          sheet: Front documentation
        - repeat_for_layer: User.Drawings
          repeat_layers: drill_pairs
          layers:
            - layer: User.Drawings
              color: '#000000'
            - layer: Edge.Cuts
              color: '#000000'
      keep_temporal_files: true
      add_background: true

  - name: basic_pcbdraw_svg_jlcpcb_green_enig_top
    comment: PCB 2D render in SVG format, using jlcpcb-green-enig style
    type: pcbdraw
    dir: PCB/2D_render/jlcpcb_green_enig
    options:
      style: jlcpcb-green-enig
      format: svg
  - name: basic_pcbdraw_png_jlcpcb_green_enig_top
    comment: PCB 2D render in PNG format, using jlcpcb-green-enig style
    type: pcbdraw
    dir: PCB/2D_render/jlcpcb_green_enig
    options:
      style: jlcpcb-green-enig
      format: png
  - name: basic_pcbdraw_svg_set_blue_enig_top
    comment: PCB 2D render in SVG format, using set-blue-enig style
    type: pcbdraw
    dir: PCB/2D_render/set_blue_enig
    options:
      style: set-blue-enig
      format: svg
  - name: basic_pcbdraw_png_set_blue_enig_top
    comment: PCB 2D render in PNG format, using set-blue-enig style
    type: pcbdraw
    dir: PCB/2D_render/set_blue_enig
    options:
      style: set-blue-enig
      format: png
  - name: basic_pcbdraw_svg_set_red_hasl_top
    comment: PCB 2D render in SVG format, using set-red-hasl style
    type: pcbdraw
    dir: PCB/2D_render/set_red_hasl
    options:
      style: set-red-hasl
      format: svg
  - name: basic_pcbdraw_png_set_red_hasl_top
    comment: PCB 2D render in PNG format, using set-red-hasl style
    type: pcbdraw
    dir: PCB/2D_render/set_red_hasl
    options:
      style: set-red-hasl
      format: png
  - name: basic_pcbdraw_svg_jlcpcb_green_enig_bottom
    comment: PCB 2D render in SVG format, using jlcpcb-green-enig style
    type: pcbdraw
    dir: PCB/2D_render/jlcpcb_green_enig
    options:
      style: jlcpcb-green-enig
      format: svg
      bottom: true
  - name: basic_pcbdraw_png_jlcpcb_green_enig_bottom
    comment: PCB 2D render in PNG format, using jlcpcb-green-enig style
    type: pcbdraw
    dir: PCB/2D_render/jlcpcb_green_enig
    options:
      style: jlcpcb-green-enig
      format: png
      bottom: true
  - name: basic_pcbdraw_svg_set_blue_enig_bottom
    comment: PCB 2D render in SVG format, using set-blue-enig style
    type: pcbdraw
    dir: PCB/2D_render/set_blue_enig
    options:
      style: set-blue-enig
      format: svg
      bottom: true
  - name: basic_pcbdraw_png_set_blue_enig_bottom
    comment: PCB 2D render in PNG format, using set-blue-enig style
    type: pcbdraw
    dir: PCB/2D_render/set_blue_enig
    options:
      style: set-blue-enig
      format: png
      bottom: true
  - name: basic_pcbdraw_svg_set_red_hasl_bottom
    comment: PCB 2D render in SVG format, using set-red-hasl style
    type: pcbdraw
    dir: PCB/2D_render/set_red_hasl
    options:
      style: set-red-hasl
      format: svg
      bottom: true
  - name: basic_pcbdraw_png_set_red_hasl_bottom
    comment: PCB 2D render in PNG format, using set-red-hasl style
    type: pcbdraw
    dir: PCB/2D_render/set_red_hasl
    options:
      style: set-red-hasl
      format: png
      bottom: true

  - name: basic_render_3d_top
    comment: 3D view from top
    type: render_3d
    dir: 3D
    options:
      ray_tracing: true
      orthographic: true
  - name: basic_render_3d_30deg
    comment: 3D view from 30 degrees
    type: render_3d
    dir: 3D
    output_id: 30deg
    options:
      ray_tracing: true
      rotate_x: 3
      rotate_z: -2
  - name: basic_render_3d_bottom
    comment: 3D view from bottom
    type: render_3d
    dir: 3D
    options:
      ray_tracing: true
      orthographic: true
      view: bottom

...
definitions:
  _KIBOT_MANF_DIR_COMP: Manufacturers
  _KIBOT_GERBER_LAYERS:
    "- layer: 'F.Cu'\n        suffix: 'F_Cu'\n        description:\
    \ 'Front copper'\n      - layer: 'B.Cu'\n        suffix: 'B_Cu'\n        description:\
    \ 'Bottom copper'\n      - layer: 'F.Paste'\n        suffix: 'F_Paste'\n     \
    \   description: 'Front solder paste'\n      - layer: 'B.Silkscreen'\n       \
    \ suffix: 'B_Silkscreen'\n        description: 'Bottom silkscreen (artwork)'\n\
    \      - layer: 'F.Silkscreen'\n        suffix: 'F_Silkscreen'\n        description:\
    \ 'Front silkscreen (artwork)'\n      - layer: 'B.Mask'\n        suffix: 'B_Mask'\n\
    \        description: 'Bottom soldermask (negative)'\n      - layer: 'F.Mask'\n\
    \        suffix: 'F_Mask'\n        description: 'Front soldermask (negative)'\n\
    \      - layer: 'Edge.Cuts'\n        suffix: 'Edge_Cuts'\n        description:\
    \ 'Board shape'"
